### ISSUE TITLE
Group Milestone 3 - Ready for Review

### ISSUE THREAD

**Issue by mikeng13** [FinNerds/AndroidApp#92]
@codepathreview and @codepath please review our project milestone 3

Our code app flows have been completed. The next milestone is UX and we are tracking that work with Githut issues.

#Milestones achieved
* [x] Client to pull financial data from the Yahoo Finance API
* [x] Pie charts, DJIA, SP500, NASDAQ and watchlist stocks to real data
* [x] Stock detail view with graph, stock data and news, with different landscape view
* [x] Add stock to watchlist from the detail view
* [x] Persistence for watchlist, stocks, and alerts
* [x] Discover tab which pulls recommended stocks from our Parse backend
* [x] Parse backend to provide stock recommendations for the discover tab
* [x] Alerts tab to view, edit, and delete alerts
* [x] Background service to poll and create notifications for alerts that have been triggered
* [x] Delete stocks from watchlist by swiping to the right
* [x] Alert creation dialog
* [x] Search by stock symbol in ActionBar

![Sprint 2 GIF](https://raw.githubusercontent.com/FinNerds/AndroidApp/master/wealthnow_sprint2_ab.gif)

@enginnerd @styliii

**Comment by codepathreview** [comment]
:+1: Nice work so far on the group project. Your team has made great progress in the last week. Hope you are proud of what you have achieved in ~6 weeks.

* Great to see that you took actions from the review comments from Sprint 1 and created milestones/issues for sprint 2.
* :+1: Good work implementing the core flows. You guys have made great progress in sprint 2 and it seems like most of your application logic is in place.
* Good to see that you have already started adding UI polish to your app, keep working hard on that
* Good job from everyone in contributing to the project, hope everyone is learning and enjoying from this
* While working on polishing your app for next sprint, remember that your app follows the [android design guidelines] (http://guides.codepath.com/android/Android-Design-Guidelines) and also benchmark your app on sites such as [android app patterns] (http://www.android-app-patterns.com/) to improve the UI/UX.

Take time this week to clean up and polish your app. Generally, most of these tasks are small and easy, but go a long way in making an impact on how your app will get perceived. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Excited to see your progress next week!
